model = "gpt-5.3-codex"
model_provider = "anyrouter"
preferred_auth_method = "apikey"
model_instructions_file = "~/.codex/prompts/system-prompt.md"
model_reasoning_effort = "medium"
personality = "pragmatic"

[model_providers.anyrouter]
name = "Any Router"
base_url = "https://anyrouter.top/v1"
wire_api = "responses"


hide_agent_reasoning = false
disable_response_storage = true

sandbox_mode = "danger-full-access"

[sandbox_workspace_write]
writable_roots = ["/dev", "/usr/local/cuda-12.6"]
network_access = true

[projects."/mnt/d/mybitcoin/2/Qwenzhuche/0402/anyauto"]
trust_level = "trusted"

[projects."/mnt/d/mybitcoin/puzzlekeyhunt/PuzzleKeyhunt"]
trust_level = "trusted"

[projects."/mnt/d/mybitcoin/linuxdo"]
trust_level = "trusted"

[projects."/mnt/d/mybitcoin/2/cuda-bsgs-production-full/Kangaroo"]
trust_level = "trusted"

[projects."/mnt/d/mybitcoin/2/Qwenzhuche/0402/anyauto/any-auto-register"]
trust_level = "trusted"

[projects."/mnt/g/mycode/mybuild"]
trust_level = "trusted"

[projects."/mnt/d/mybitcoin/gaokao"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]
type = "stdio"
startup_timeout_sec = 45

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
type = "stdio"
startup_timeout_sec = 45

[mcp_servers.mcp-server-time]
command = "uvx"
args = ["mcp-server-time", "--local-timezone=Asia/Shanghai"]
type = "stdio"
startup_timeout_sec = 45

[mcp_servers.mcp-deepwiki]
command = "npx"
args = ["-y", "mcp-deepwiki@latest"]
type = "stdio"
startup_timeout_sec = 120

[mcp_servers.desktop-commander]
command = "desktop-commander"
args = []
type = "stdio"
startup_timeout_sec = 120

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
