steps:
  - name: deploy
    image: docker:cli
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
