run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
<<<<<<< HEAD

output:
  formats:
    - format: colored-line-number
=======
  skip-dirs:
    - vendor
    - bin
    - .git
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"

output:
  format: colored-line-number
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  godot:
    scope: declarations
    capital: false
  goimports:
    local-prefixes: github.com/gaokaohub
<<<<<<< HEAD
  govet:
    enable:
      - shadow
=======
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  govet:
    check-shadowing: true
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
<<<<<<< HEAD
=======
  maligned:
    suggest-new: true
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
<<<<<<< HEAD
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

linters:
  # Enable only active and maintained linters
  enable:
    - bodyclose
=======

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
    - depguard
    - dogsled
    - dupl
    - errcheck
<<<<<<< HEAD
=======
    - exportloopref
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
<<<<<<< HEAD
=======
    - gomnd
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
<<<<<<< HEAD
=======
    - structcheck
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
<<<<<<< HEAD
    - whitespace
    - revive
    - mnd

issues:
  exclude-dirs:
    - vendor
    - bin
    - .git
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
=======
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
        - funlen
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: cmd/
      linters:
<<<<<<< HEAD
        - mnd
=======
        - gomnd
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
    - linters:
        - lll
      source: "^//go:generate "
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - misspell
<<<<<<< HEAD
      severity: warning
=======
      severity: warning
>>>>>>> 0dd6b27ce36fbec25f47c1952ba01974d6d592bc
