# DeviceFingerprintConfig.cmake.in - CMake configuration file for DeviceFingerprint
# This file is auto-generated by CMake


####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was DeviceFingerprintConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

# Package information
set(DeviceFingerprint_VERSION "1.0.0")
set(DeviceFingerprint_VERSION_MAJOR 1)
set(DeviceFingerprint_VERSION_MINOR 0)
set(DeviceFingerprint_VERSION_PATCH 0)

# Installation paths
set(DeviceFingerprint_INCLUDE_DIRS "")
set(DeviceFingerprint_LIBRARY_DIRS "")
set(DeviceFingerprint_BINARY_DIRS "")

# Build configuration
set(DeviceFingerprint_BUILD_TYPE "Release")
set(DeviceFingerprint_CXX_STANDARD 17)
set(DeviceFingerprint_COMPILER_ID "GNU")
set(DeviceFingerprint_COMPILER_VERSION "13.3.0")

# Feature flags
set(DeviceFingerprint_BUILD_TESTS ON)
set(DeviceFingerprint_BUILD_EXAMPLES ON)
set(DeviceFingerprint_BUILD_BENCHMARKS OFF)
set(DeviceFingerprint_BUILD_GO_BINDINGS ON)

# Dependencies
set(DeviceFingerprint_OPENSSL_VERSION "3.0.13")
set(DeviceFingerprint_REQUIRES_OPENSSL TRUE)

# Check if all required components are available
check_required_components(DeviceFingerprint)

# Find and set up dependencies
find_dependency(OpenSSL REQUIRED)
find_dependency(Threads REQUIRED)

# Import targets
if(NOT TARGET DeviceFingerprint::DeviceFingerprint)
    include("${CMAKE_CURRENT_LIST_DIR}/DeviceFingerprintTargets.cmake")
endif()

# Set up library targets
set(DeviceFingerprint_LIBRARIES DeviceFingerprint::DeviceFingerprint)
set(DeviceFingerprint_STATIC_LIBRARIES DeviceFingerprint::DeviceFingerprint_static)
set(DeviceFingerprint_SHARED_LIBRARIES DeviceFingerprint::DeviceFingerprint_shared)

# Compatibility aliases
if(NOT TARGET DeviceFingerprint)
    add_library(DeviceFingerprint ALIAS DeviceFingerprint::DeviceFingerprint)
endif()

# Helper function to link DeviceFingerprint to a target
function(target_link_device_fingerprint target)
    target_link_libraries(${target} PRIVATE DeviceFingerprint::DeviceFingerprint)
    target_include_directories(${target} PRIVATE ${DeviceFingerprint_INCLUDE_DIRS})
endfunction()

# Print configuration summary
if(NOT DeviceFingerprint_FIND_QUIETLY)
    message(STATUS "Found DeviceFingerprint: ${DeviceFingerprint_VERSION}")
    message(STATUS "  Include dirs: ${DeviceFingerprint_INCLUDE_DIRS}")
    message(STATUS "  Library dirs: ${DeviceFingerprint_LIBRARY_DIRS}")
    message(STATUS "  Libraries: ${DeviceFingerprint_LIBRARIES}")
    message(STATUS "  Build type: ${DeviceFingerprint_BUILD_TYPE}")
    message(STATUS "  C++ standard: ${DeviceFingerprint_CXX_STANDARD}")
    message(STATUS "  OpenSSL version: ${DeviceFingerprint_OPENSSL_VERSION}")
endif()
