// Package volunteermatcher provides Go bindings for the Volunteer Matcher C++ library
// This file is auto-generated by CMake from volunteer_matcher.go.in
package volunteermatcher

/*
#cgo CXXFLAGS: -std=c++17 -DENABLE_ONNX_RUNTIME
#cgo CFLAGS: -I/usr/local/include
#cgo LDFLAGS: -L/usr/local/lib -lvolunteer_matcher
#include <volunteer_matcher.h>
*/
import "C"
import (
	"errors"
	"unsafe"
)

// Version information
const (
	VersionMajor = 1
	VersionMinor = 0
	VersionPatch = 0
	Version      = "1.0.0"
)

// VolunteerMatcher represents a volunteer matcher engine
type VolunteerMatcher struct {
	ptr unsafe.Pointer
}

// NewVolunteerMatcher creates a new volunteer matcher engine
func NewVolunteerMatcher() (*VolunteerMatcher, error) {
	ptr := C.volunteer_matcher_create()
	if ptr == nil {
		return nil, errors.New("failed to create volunteer matcher engine")
	}
	return &VolunteerMatcher{ptr: ptr}, nil
}

// Destroy releases the volunteer matcher engine resources
func (vm *VolunteerMatcher) Destroy() {
	if vm.ptr != nil {
		C.volunteer_matcher_destroy(vm.ptr)
		vm.ptr = nil
	}
}

// Initialize initializes the volunteer matcher engine
func (vm *VolunteerMatcher) Initialize(configPath string) error {
	if vm.ptr == nil {
		return errors.New("volunteer matcher engine is not initialized")
	}

	cConfigPath := C.CString(configPath)
	defer C.free(unsafe.Pointer(cConfigPath))

	result := C.volunteer_matcher_initialize(vm.ptr, cConfigPath)
	if result != 0 {
		return errors.New("failed to initialize volunteer matcher engine")
	}

	return nil
}

// LoadUniversities loads university data
func (vm *VolunteerMatcher) LoadUniversities(filePath string) (int, error) {
	if vm.ptr == nil {
		return 0, errors.New("volunteer matcher engine is not initialized")
	}

	cFilePath := C.CString(filePath)
	defer C.free(unsafe.Pointer(cFilePath))

	count := int(C.volunteer_matcher_load_universities(vm.ptr, cFilePath))
	if count < 0 {
		return 0, errors.New("failed to load university data")
	}

	return count, nil
}

// LoadMajors loads major data
func (vm *VolunteerMatcher) LoadMajors(filePath string) (int, error) {
	if vm.ptr == nil {
		return 0, errors.New("volunteer matcher engine is not initialized")
	}

	cFilePath := C.CString(filePath)
	defer C.free(unsafe.Pointer(cFilePath))

	count := int(C.volunteer_matcher_load_majors(vm.ptr, cFilePath))
	if count < 0 {
		return 0, errors.New("failed to load major data")
	}

	return count, nil
}

// GenerateVolunteerPlan generates a volunteer plan
func (vm *VolunteerMatcher) GenerateVolunteerPlan(studentJSON string, maxVolunteers int) (string, error) {
	if vm.ptr == nil {
		return "", errors.New("volunteer matcher engine is not initialized")
	}

	cStudentJSON := C.CString(studentJSON)
	defer C.free(unsafe.Pointer(cStudentJSON))

	cResult := C.volunteer_matcher_generate_plan(vm.ptr, cStudentJSON, C.int(maxVolunteers))
	if cResult == nil {
		return "", errors.New("failed to generate volunteer plan")
	}

	result := C.GoString(cResult)
	C.free(unsafe.Pointer(cResult))
	return result, nil
}